export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/index.html.js"), meta: {"t":"Home"} }],
  ["/about/about.html", { loader: () => import(/* webpackChunkName: "about_about.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/about/about.html.js"), meta: {"t":"About","i":"address-card"} }],
  ["/contact/contact.html", { loader: () => import(/* webpackChunkName: "contact_contact.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/contact/contact.html.js"), meta: {"t":"Contact","i":"envolope"} }],
  ["/pages/20241210%20welcome%20page.html", { loader: () => import(/* webpackChunkName: "pages_20241210 welcome page.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/pages/20241210 welcome page.html.js"), meta: {"a":"Sengly MUY","d":1733788800000,"l":"December 10, 2024","c":["Welcome"],"g":["Welcome"],"u":false,"e":"<h2>Welcome to my blog.</h2>\n","r":{"minutes":0.11,"words":32},"t":"Welcome","i":"file","O":1,"y":"a"} }],
  ["/webinar/webinar_001.html", { loader: () => import(/* webpackChunkName: "webinar_webinar_001.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/webinar/webinar_001.html.js"), meta: {"a":"Unknow","d":946684800000,"l":"January 1, 2000","c":["Webinar"],"g":["Webinar"],"u":false,"e":"<h2>Webinar</h2>\n<p>SpaceX's Starlink has already deployed 6,006 LEO satellites in space to provide internet access to users around the globe and has now reached 3 million subscribers. Are you ready to gain insights into space networks? Join us for a transformative webinar where we’ll delve into the research on space networks.\nJoin us via zoom: https://ncsu.zoom.us/j/3810472620...</p>","r":{"minutes":0.34,"words":102},"t":"Webinar 001","i":"tv","y":"a"} }],
  ["/webinar/webinar_002.html", { loader: () => import(/* webpackChunkName: "webinar_webinar_002.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/webinar/webinar_002.html.js"), meta: {"a":"Unknow","d":946684800000,"l":"January 1, 2000","c":["Webinar"],"g":["Webinar"],"u":false,"e":"<h2>Webinar</h2>\n<p>We are excited to invite you to join our webinar to gain insights into network security. Our speaker has successfully proposed a method that secures the data transmission rate for legitimate receiver under interception by eavesdropper, while accounting for imperfect channel estimation. His study was accepted to publish in IEEE TVT, which is a high-quality journal.</p>","r":{"minutes":0.38,"words":113},"t":"Webinar 002","i":"tv","y":"a"} }],
  ["/webinar/webinar_003.html", { loader: () => import(/* webpackChunkName: "webinar_webinar_003.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/webinar/webinar_003.html.js"), meta: {"a":"Unknow","d":946684800000,"l":"January 1, 2000","c":["Webinar"],"g":["Webinar"],"u":false,"e":"<h2>Webinar</h2>\n<p>We are excited to invite you to our upcoming webinar, where we will delve deeper into material properties and antenna design. Our speaker is currently a lecturer and researcher at the Cambodia Academy of Digital Technology (CATD). He has published multiple research articles on this topic in international journals and conferences.</p>","r":{"minutes":0.36,"words":108},"t":"Webinar 003","i":"tv","y":"a"} }],
  ["/webinar/webinar_004.html", { loader: () => import(/* webpackChunkName: "webinar_webinar_004.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/webinar/webinar_004.html.js"), meta: {"a":"Unknow","d":946684800000,"l":"January 1, 2000","c":["Webinar"],"g":["Webinar"],"u":false,"e":"<h2>Webinar</h2>\n<p>យើងមានសេចក្តីរីករាយក្នុងការអញ្ជើញលោកអ្នកទាំងអស់គ្នាចូលរួមសិក្ខាសាលារបស់យើងក្រោមប្រធានបទ \"A Novel Approach to Student Behavior Classification Using Deep Learning\" ជាមួយនឹងសាស្ត្រាចារ្យមកពីសាកលវិទ្យាល័យមួយនៃប្រទេសថៃ។ លោកនឹងធ្វើបទបង្ហាញទាក់ទងនឹងការប្រើប្រាស់ AI ដើម្បីលើកកម្ពស់លទ្ធផលសិក្សារបស់សិស្ស។</p>","r":{"minutes":0.41,"words":122},"t":"Webinar 004","i":"tv","y":"a"} }],
  ["/webinar/webinar_005.html", { loader: () => import(/* webpackChunkName: "webinar_webinar_005.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/webinar/webinar_005.html.js"), meta: {"a":"Unknow","d":946684800000,"l":"January 1, 2000","c":["Webinar"],"g":["Webinar"],"u":false,"e":"<h2>Webinar</h2>\n<p>យើងមានសេចក្តីរីករាយក្នុងការអញ្ជើញលោកអ្នកទាំងអស់គ្នាចូលរួមសិក្ខាសាលារបស់យើងក្រោមប្រធានបទ \"Efficient Pig Sounds Classification Using a Lightweight CNN Model\" ជាមួយនឹងអ្នកស្រាវជ្រាវមកពីវិទ្យាស្ថានស្រាវជ្រាវ NIAS របស់ប្រទេសកូរ៉េ។ លោកនឹងធ្វើបទបង្ហាញទាក់ទងនឹងការប្រើប្រាស់ Machine Learning ទៅក្នុងកសិកម្មចិញ្ចឹមជ្រូក។</p>","r":{"minutes":0.38,"words":114},"t":"Webinar 005","i":"tv","y":"a"} }],
  ["/webinar/webinar_006.html", { loader: () => import(/* webpackChunkName: "webinar_webinar_006.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/webinar/webinar_006.html.js"), meta: {"a":"Unknow","d":946684800000,"l":"January 1, 2000","c":["Webinar"],"g":["Webinar"],"u":false,"e":"<h2>Webinar</h2>\n<p>យើងមានសេចក្តីរីករាយក្នុងការអញ្ជើញលោកអ្នកទាំងអស់គ្នាចូលរួមសិក្ខាសាលារបស់យើងក្រោមប្រធានបទ \"A Modified Vector Fitting Technique To Extract Coupling Matrix From S-Parameters\" ជាមួយនឹងលោកបណ្ឌិត Socheatra Soeung មកពី Universiti Teknologi PETRONAS របស់ប្រទេសម៉ាឡេស៊ី។</p>\n<p>We are excited to invite you to participate in our webinar on a topic of \"A Modified Vector Fitting Technique To Extract Coupling Matrix From S-Parameters\" presented by Dr. Socheatra Soeung from Univeristi Teknologi PETRONAS of Malaysia.</p>","r":{"minutes":0.46,"words":139},"t":"Webinar 006","i":"tv","y":"a"} }],
  ["/classes/class_01/file_001.html", { loader: () => import(/* webpackChunkName: "classes_class_01_file_001.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/classes/class_01/file_001.html.js"), meta: {"t":"File_01","i":"star"} }],
  ["/classes/class_01/file_002.html", { loader: () => import(/* webpackChunkName: "classes_class_01_file_002.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/classes/class_01/file_002.html.js"), meta: {"t":"File_02","i":"star"} }],
  ["/classes/class_02/file_001.html", { loader: () => import(/* webpackChunkName: "classes_class_02_file_001.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/classes/class_02/file_001.html.js"), meta: {"t":"File_01","i":"star"} }],
  ["/classes/class_02/file_002.html", { loader: () => import(/* webpackChunkName: "classes_class_02_file_002.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/classes/class_02/file_002.html.js"), meta: {"t":"File_02","i":"star"} }],
  ["/demo/001/001.layout.html", { loader: () => import(/* webpackChunkName: "demo_001_001.layout.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/001.layout.html.js"), meta: {"t":"1. Layout","i":"object-group","O":1} }],
  ["/demo/001/002.markdown.html", { loader: () => import(/* webpackChunkName: "demo_001_002.markdown.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/002.markdown.html.js"), meta: {"t":"2. Markdown Enhance","i":"fab fa-markdown","O":2} }],
  ["/demo/001/003.page.html", { loader: () => import(/* webpackChunkName: "demo_001_003.page.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/003.page.html.js"), meta: {"t":"3. Page Config","i":"file","O":3} }],
  ["/demo/001/004.disable.html", { loader: () => import(/* webpackChunkName: "demo_001_004.disable.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/004.disable.html.js"), meta: {"t":"4. Disabling Layout","i":"gears","O":4} }],
  ["/demo/001/005.encrypt.html", { loader: () => import(/* webpackChunkName: "demo_001_005.encrypt.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/005.encrypt.html.js"), meta: {"t":"5. Encrypt Layout","i":"lock","O":5} }],
  ["/demo/001/006.water%20mark.html", { loader: () => import(/* webpackChunkName: "demo_001_006.water mark.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/006.water mark.html.js"), meta: {"t":"6. Water-Mark","i":"water","O":6} }],
  ["/demo/001/007.cover.html", { loader: () => import(/* webpackChunkName: "demo_001_007.cover.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/007.cover.html.js"), meta: {"t":"7. Cover","i":"star","O":7} }],
  ["/demo/001/008.home.with.feature.html", { loader: () => import(/* webpackChunkName: "demo_001_008.home.with.feature.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/008.home.with.feature.html.js"), meta: {"t":"8. Home with features","i":"home","O":8} }],
  ["/demo/001/009.home.html", { loader: () => import(/* webpackChunkName: "demo_001_009.home.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/009.home.html.js"), meta: {"t":"9. Home","i":"home","O":9} }],
  ["/demo/001/010.image.preview.html", { loader: () => import(/* webpackChunkName: "demo_001_010.image.preview.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/010.image.preview.html.js"), meta: {"t":"10. Image Preview","i":"image","O":10} }],
  ["/demo/001/011.page.info.html", { loader: () => import(/* webpackChunkName: "demo_001_011.page.info.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/011.page.info.html.js"), meta: {"t":"11. Page information","i":"circle-info","O":11} }],
  ["/demo/001/012.buitin.component.html", { loader: () => import(/* webpackChunkName: "demo_001_012.buitin.component.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/012.buitin.component.html.js"), meta: {"t":"12. Built-in Components","i":"puzzle-piece","O":12} }],
  ["/demo/001/013.image.html", { loader: () => import(/* webpackChunkName: "demo_001_013.image.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/013.image.html.js"), meta: {"t":"13. Image","i":"image","O":13} }],
  ["/demo/001/014.content.html", { loader: () => import(/* webpackChunkName: "demo_001_014.content.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/014.content.html.js"), meta: {"t":"14. Content","i":"pen","O":14} }],
  ["/demo/001/015.include.vue.html", { loader: () => import(/* webpackChunkName: "demo_001_015.include.vue.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/015.include.vue.html.js"), meta: {"t":"15. Include VUE","i":"star","O":15} }],
  ["/demo/001/016.vue.in.markdown.html", { loader: () => import(/* webpackChunkName: "demo_001_016.vue.in.markdown.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/016.vue.in.markdown.html.js"), meta: {"t":"16. VUE in MD","i":"star","O":16} }],
  ["/demo/001/017.customize.home.html", { loader: () => import(/* webpackChunkName: "demo_001_017.customize.home.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/017.customize.home.html.js"), meta: {"t":"17. Customized Home","i":"star","O":17} }],
  ["/demo/001/", { loader: () => import(/* webpackChunkName: "demo_001_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/001/index.html.js"), meta: {"t":"1. Features demo","i":"star"} }],
  ["/demo/002/001_template.html", { loader: () => import(/* webpackChunkName: "demo_002_001_template.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/001_template.html.js"), meta: {"t":"2.1. Template","i":"star","O":1} }],
  ["/demo/002/cherry.html", { loader: () => import(/* webpackChunkName: "demo_002_cherry.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/cherry.html.js"), meta: {"t":"Cherry","i":"star"} }],
  ["/demo/002/dragonfruit.html", { loader: () => import(/* webpackChunkName: "demo_002_dragonfruit.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/dragonfruit.html.js"), meta: {"t":"Dragon Fruit","i":"star"} }],
  ["/demo/002/", { loader: () => import(/* webpackChunkName: "demo_002_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/index.html.js"), meta: {"t":"2. Other Demo","i":"star"} }],
  ["/demo/002/strawberry.html", { loader: () => import(/* webpackChunkName: "demo_002_strawberry.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/strawberry.html.js"), meta: {"t":"Strawberry","i":"star"} }],
  ["/demo/002/tomato.html", { loader: () => import(/* webpackChunkName: "demo_002_tomato.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/tomato.html.js"), meta: {"t":"Tomato","i":"star"} }],
  ["/demo/002/002.002/1.html", { loader: () => import(/* webpackChunkName: "demo_002_002.002_1.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.002/1.html.js"), meta: {"t":"Apple 1","i":"star"} }],
  ["/demo/002/002.002/2.html", { loader: () => import(/* webpackChunkName: "demo_002_002.002_2.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.002/2.html.js"), meta: {"t":"Apple 2","i":"star"} }],
  ["/demo/002/002.002/3.html", { loader: () => import(/* webpackChunkName: "demo_002_002.002_3.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.002/3.html.js"), meta: {"t":"Apple 3","i":"star"} }],
  ["/demo/002/002.002/4.html", { loader: () => import(/* webpackChunkName: "demo_002_002.002_4.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.002/4.html.js"), meta: {"t":"Apple 4","i":"star"} }],
  ["/demo/002/002.002/", { loader: () => import(/* webpackChunkName: "demo_002_002.002_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.002/index.html.js"), meta: {"t":"2.2. Apple","i":"star"} }],
  ["/demo/002/002.003/1.html", { loader: () => import(/* webpackChunkName: "demo_002_002.003_1.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.003/1.html.js"), meta: {"t":"Banana 1","i":"star"} }],
  ["/demo/002/002.003/2.html", { loader: () => import(/* webpackChunkName: "demo_002_002.003_2.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.003/2.html.js"), meta: {"t":"Banana 2","i":"star"} }],
  ["/demo/002/002.003/3.html", { loader: () => import(/* webpackChunkName: "demo_002_002.003_3.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.003/3.html.js"), meta: {"t":"Banana 3","i":"star"} }],
  ["/demo/002/002.003/4.html", { loader: () => import(/* webpackChunkName: "demo_002_002.003_4.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.003/4.html.js"), meta: {"t":"Banana 4","i":"star"} }],
  ["/demo/002/002.003/", { loader: () => import(/* webpackChunkName: "demo_002_002.003_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/002/002.003/index.html.js"), meta: {"t":"2.3. Banana","i":"star"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/404.html.js"), meta: {"t":""} }],
  ["/about/", { loader: () => import(/* webpackChunkName: "about_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/about/index.html.js"), meta: {"t":"About"} }],
  ["/contact/", { loader: () => import(/* webpackChunkName: "contact_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/contact/index.html.js"), meta: {"t":"Contact"} }],
  ["/pages/", { loader: () => import(/* webpackChunkName: "pages_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/pages/index.html.js"), meta: {"t":"Pages"} }],
  ["/webinar/", { loader: () => import(/* webpackChunkName: "webinar_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/webinar/index.html.js"), meta: {"t":"Webinar"} }],
  ["/classes/class_01/", { loader: () => import(/* webpackChunkName: "classes_class_01_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/classes/class_01/index.html.js"), meta: {"t":"Class 01"} }],
  ["/classes/", { loader: () => import(/* webpackChunkName: "classes_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/classes/index.html.js"), meta: {"t":"Classes"} }],
  ["/classes/class_02/", { loader: () => import(/* webpackChunkName: "classes_class_02_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/classes/class_02/index.html.js"), meta: {"t":"Class 02"} }],
  ["/demo/", { loader: () => import(/* webpackChunkName: "demo_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/demo/index.html.js"), meta: {"t":"Demo"} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "category_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/category/index.html.js"), meta: {"t":"Category","I":false} }],
  ["/category/welcome/", { loader: () => import(/* webpackChunkName: "category_welcome_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/category/welcome/index.html.js"), meta: {"t":"Welcome Category","I":false} }],
  ["/category/webinar/", { loader: () => import(/* webpackChunkName: "category_webinar_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/category/webinar/index.html.js"), meta: {"t":"Webinar Category","I":false} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "tag_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/tag/index.html.js"), meta: {"t":"Tag","I":false} }],
  ["/tag/welcome/", { loader: () => import(/* webpackChunkName: "tag_welcome_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/tag/welcome/index.html.js"), meta: {"t":"Tag: Welcome","I":false} }],
  ["/tag/webinar/", { loader: () => import(/* webpackChunkName: "tag_webinar_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/tag/webinar/index.html.js"), meta: {"t":"Tag: Webinar","I":false} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "article_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/article/index.html.js"), meta: {"t":"Articles","I":false} }],
  ["/star/", { loader: () => import(/* webpackChunkName: "star_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/star/index.html.js"), meta: {"t":"Star","I":false} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "timeline_index.html" */"C:/Users/muysengly/Desktop/my_github/cics/src/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"t":"Timeline","I":false} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
